githubpage:
    build: "/home/gonz/code/racket/github-page"
    ports:
        - "8080:8080"
moviestarpage:
    build: "/home/gonz/code/racket/movie-star"
    ports:
        - "8082:8082"
    volumes:
        - "~/code/racket/movie-star/cache:/cache/"
        - "~/code/racket/movie-star/posters:/movie-star/posters/"
wikipage:
    build: "/home/gonz/code/racket/mediawiki-api"
    ports:
        - "8083:8083"
web:
    build: "/home/gonz/code/docker/gonz/web-router"
    ports:
        - "80:80"
    links:
        - githubpage
        - moviestarpage
        - wikipage
    volumes:
        - "~/code/racket/github-page/src/static:/github/static/"
        - "~/code/racket/movie-star/posters:/movie-star/posters/"
